name: Fuzz parser

on:
  push:
    branches: [master]
    paths:
      - src/scanner.c
      - src/keywords.h
  pull_request:
    paths:
      - src/scanner.c
      - src/keywords.h

jobs:
  fuzz:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/fuzz-action@v4
